#ifndef CONFIG_MODES_H
#define CONFIG_MODES_H

#define ENABLE_MODE_ASYNC 1
#define ENABLE_MODE_SYNC 1
#define ENABLE_MODE_THREAD 1
#define ENABLE_MODE_CHAMFER 1
#define ENABLE_MODE_CONE 1
#define ENABLE_MODE_SPHERE 1
#define ENABLE_MODE_DIVIDER 1
#define ENABLE_MODE_GRIND 1

#endif